name: Node.js Package

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true
      - run: pnpm build
      - name: Publish Package
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          pnpm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          pnpm publish --access public --no-git-checks
